/**
 * /api/legal — serves BOTH the privacy policy and terms of service.
 *   /api/legal?page=privacy  (default)
 *   /api/legal?page=terms
 * Replaces privacy.js and terms.js to stay under Vercel Hobby's 12-function cap.
 */
export default function handler(req, res) {
  const page = (req.query.page || "privacy").toLowerCase();
  res.setHeader("Content-Type", "text/html");

  const shell = (title, body) => `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} — ReportForge AI</title>
<style>*{box-sizing:border-box}body{background:#07111F;color:#F1F5F9;font-family:-apple-system,sans-serif;max-width:720px;margin:0 auto;padding:40px 20px;line-height:1.7}nav{display:flex;align-items:center;gap:10px;margin-bottom:32px;border-bottom:1px solid #1E293B;padding-bottom:16px}.dot{width:9px;height:9px;border-radius:50%;background:#F59E0B}.logo{font-weight:700;font-size:15px}h1{font-size:26px;font-weight:500;margin-bottom:6px;color:#F8FAFC}h2{font-size:16px;font-weight:500;margin:28px 0 8px;color:#F59E0B}p,li{font-size:14px;color:#94A3B8;margin-bottom:8px}ul{padding-left:20px}a{color:#F59E0B}footer{margin-top:40px;padding-top:16px;border-top:1px solid #1E293B;font-size:12px;color:#475569}</style>
</head><body>
<nav><div class="dot"></div><span class="logo">ReportForge AI</span></nav>
${body}
</body></html>`;

  if (page === "terms") {
    return res.status(200).send(shell("Terms of Service", `
<h1>Terms of Service</h1>
<p>Last updated: June 2026</p>
<h2>Acceptance</h2>
<p>By using ReportForge AI you agree to these terms. If you do not agree, do not use the service.</p>
<h2>Service description</h2>
<p>ReportForge AI generates AI-powered market intelligence reports using Claude AI. Reports are for informational purposes only and do not constitute financial, investment, or legal advice.</p>
<h2>Report accuracy</h2>
<p>Reports are generated by AI and may contain inaccuracies. We do not guarantee the accuracy, completeness, or timeliness of any report. Always verify data from authoritative sources before making business decisions.</p>
<h2>Free trial</h2>
<p>Free trial users receive one complimentary report. No credit card is required for the free trial. Free trial access may be withdrawn at any time.</p>
<h2>Paid subscriptions</h2>
<p>Paid plans are billed monthly through Lemon Squeezy. You may cancel at any time. Cancellations take effect at the end of the current billing period. No refunds are issued for partial months.</p>
<h2>Acceptable use</h2>
<p>You may not use ReportForge AI to generate reports for unlawful purposes, resell outputs without attribution, or attempt to reverse-engineer the underlying systems.</p>
<h2>Intellectual property</h2>
<p>Reports generated by ReportForge AI are yours to use for your own business purposes. The ReportForge AI platform, codebase, and brand remain the property of MindMaverik Media.</p>
<h2>Limitation of liability</h2>
<p>ReportForge AI is provided "as is". We are not liable for any business decisions made based on report outputs. Maximum liability is limited to the amount paid in the previous 30 days.</p>
<h2>Contact</h2>
<p><a href="mailto:mindmaverikmedia@gmail.com">mindmaverikmedia@gmail.com</a></p>
<footer>© 2026 ReportForge AI · <a href="/api/legal?page=privacy">Privacy Policy</a> · <a href="/">Back to app</a></footer>`));
  }

  // Default: privacy policy
  return res.status(200).send(shell("Privacy Policy", `
<h1>Privacy Policy</h1>
<p>Last updated: June 2026</p>
<p>ReportForge AI ("we", "us", "our") operates reportforge-2ap7.vercel.app. This policy explains how we collect, use, and protect your information.</p>
<h2>Information we collect</h2>
<ul>
<li>Email address and first name when you sign up for a free trial or paid plan</li>
<li>Market topics and geographic regions you enter when generating reports</li>
<li>Usage data including pages visited and features used (via Vercel Analytics)</li>
<li>Payment information processed by Lemon Squeezy or Gumroad — we do not store card details</li>
</ul>
<h2>How we use your information</h2>
<ul>
<li>To deliver the market intelligence reports you request</li>
<li>To send onboarding emails and product updates (you can unsubscribe at any time)</li>
<li>To improve the product and fix issues</li>
<li>We do not sell, rent, or share your personal data with third parties for marketing purposes</li>
</ul>
<h2>LinkedIn data</h2>
<p>If you connect via LinkedIn (for Lead Gen Forms or authentication), we receive your name, email address, job title, and company name as provided by LinkedIn. This data is used solely to deliver your free trial access and enroll you in our onboarding sequence.</p>
<h2>Data retention</h2>
<p>We retain your email address and usage history for as long as your account is active. You may request deletion at any time by emailing us.</p>
<h2>Your rights</h2>
<p>You may request access to, correction of, or deletion of your personal data at any time. To exercise these rights, contact: mindmaverikmedia@gmail.com</p>
<h2>Cookies</h2>
<p>We use only essential cookies required for the application to function. We do not use advertising or tracking cookies.</p>
<h2>Contact</h2>
<p>Questions about this policy: <a href="mailto:mindmaverikmedia@gmail.com">mindmaverikmedia@gmail.com</a></p>
<footer>© 2026 ReportForge AI · <a href="/api/legal?page=terms">Terms of Service</a> · <a href="/">Back to app</a></footer>`));
}
